name: CI

on:
  pull_request: null
  push:
    branches:
      - 1.x
  schedule:
    - cron: "45 7 * * 1"

jobs:
  Tests:
    name: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony-version }}${{ matrix.description }}
    runs-on: ubuntu-latest
    env:
      SYMFONY_DEPRECATIONS_HELPER: 'max[self]=0'
    strategy:
      matrix:
        php:
          - '8.4'
          - '8.3'
          - '8.2'
        symfony-version: ['']
        include:
          - php: '8.5'
            composer_options: '--ignore-platform-req=php+'
          - symfony-version: '^8.0.0-BETA1'
            composer-minimum-stability: 'beta'
            php: '8.4'
          - symfony-version: '^7.3'
            php: '8.3'
          - symfony-version: '^6.4'
            php: '8.2'
          - php: '8.2'
            dependencies: 'prefer-lowest'
            env:
              SYMFONY_DEPRECATIONS_HELPER: 'disabled'

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2 # needed by codecov sometimes
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: flex
      - name: Configure Composer minimum-stability
        if: matrix.composer-minimum-stability
        run: composer config minimum-stability ${{ matrix.composer-minimum-stability }}
      - name: Remove Composer unneeded dependencies
        run: composer remove --dev --no-update vimeo/psalm psalm/plugin-phpunit facile-it/facile-coding-standard
      - name: Install dependencies
        uses: "ramsey/composer-install@v4"
        with:
          composer-options: ${{ matrix.composer_options }}
          dependency-versions: "${{ matrix.dependencies }}"
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v6
        with:
          files: './coverage.xml'
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
  SA:
    strategy:
      matrix:
        include:
          - description: Composer checks
            script: vendor/bin/composer-dependency-analyser && composer validate
          - description: Code style
            script: vendor/bin/php-cs-fixer fix --ansi --verbose --dry-run
          - description: Rector
            script: vendor/bin/rector --ansi --dry-run
          - description: PHPStan
            script: vendor/bin/phpstan analyze
          - description: Psalm
            script: vendor/bin/psalm

    name: ${{ matrix.description }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Install dependencies
        uses: "ramsey/composer-install@v4"
      - run: ${{ matrix.script }}
