name: Static analysis

on:
  pull_request: ~
  push:
    branches:
      - master
  schedule:
    - cron: "45 7 * * 1"

jobs:
  job:
    strategy:
      matrix:
        include:
          - description: Validate composer.json
            script: composer validate
          - description: Code style
            script: vendor/bin/php-cs-fixer fix --ansi --verbose --dry-run
          - description: PHPStan
            script: vendor/bin/phpstan analyze
          - description: Psalm
            script: vendor/bin/psalm

    name: ${{ matrix.description }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
      - run: ${{ matrix.script }}
