name: Tests

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  Tests:
    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    env:
      SYMFONY_DEPRECATIONS_HELPER: 'max[self]=0'
    strategy:
      matrix:
        php:
          - '8.0'
          - '7.4'
          - '7.3'
        symfony: ['']
        experimental: [false]
        include:
          - symfony: '^4.4'
            os: 'ubuntu-latest'
            php: '7.4'
          - symfony: '^3.4'
            os: 'ubuntu-latest'
            php: '7.4'
          - description: 'Prefer lowest'
            os: 'ubuntu-latest'
            php: '7.3'
            dependencies: '--prefer-lowest'
            env:
              SYMFONY_DEPRECATIONS_HELPER: 'disabled'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # needed by codecov sometimes
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: Restrict Symfony version
        run: composer require --dev "symfony/symfony:${{ matrix.symfony }}" --no-update
        if: matrix.symfony
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: './coverage.xml'
          fail_ci_if_error: true
