name: CI

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == true }}
    env:
      SYMFONY_DEPRECATIONS_HELPER: 'max[self]=0'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php:
          - '7.4'
          - '7.3'
          - '7.2'
        composer_option: ['']
        experimental: [false]
        include:
#          - description: 'nightly'
#            os: 'ubuntu-latest'
#            php: '8.0'
          - description: 'Prefer lowest'
            os: 'ubuntu-latest'
            php: '7.2'
            composer_option: '--prefer-lowest'
            env:
              SYMFONY_DEPRECATIONS_HELPER: 'disabled'

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ matrix.php }}${{ matrix.composer_option }} 
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - run: composer update --no-progress --ansi ${{ matrix.composer_option }}
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: './coverage.xml'
          fail_ci_if_error: true
